MebelMarket/Controllers/FurnitureController.cs
using MebelMarket.Infrastructure.Interfaces;
using MebelMarket.Infrastructure.Mapping;
using Microsoft.AspNetCore.Http;
using MebelMarket.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using Microsoft.AspNetCore.Hosting;
using MebelMarket.Infrastructure.Services.Notify;
using System.Threading.Tasks;

namespace MebelMarket.Controllers
{
    public class FurnitureController : Controller
    {
        private readonly IFurnitureData _FurnitureData;
        private readonly IWebHostEnvironment _environment;
        private readonly Notify _notify;

        public FurnitureController(IFurnitureData FurnitureData, IWebHostEnvironment environment, Notify notify)
        {
            _FurnitureData = FurnitureData;
            _environment = environment;
            _notify = notify;
        }

        public IActionResult Index(int? id, [FromQuery(Name = "filter")] string filter = null)
        {
            if (id == null)
                return View(nameof(Grid));

            if (id < 0)
                return BadRequest();

            if (id == 0)
            {
                var lastFurnitures = _FurnitureData.GetLastFurnitures().Take(21);

                return View(lastFurnitures.ToView());
            }

            var furniture = _FurnitureData.GetById(id.Value);

            var wwwroot = _environment.WebRootPath;
            ViewBag.wwwroot = wwwroot;
            ViewBag.filter = filter == "forOffice"
                ? "forOffice"
                : filter == "forHome"
                    ? "forHome"
                    : null;

            return View(furniture.ToView());
        }

        public IActionResult Grid(int? id, 
            [FromQuery(Name = "page")] string pageId, 
            [FromForm(Name = "sortOrder")] string sortOrder = null, 
            [FromQuery(Name = "filter")] string filter = null)
        {
            ViewBag.filter = filter == "forOffice"
            ? "forOffice"
            : filter == "forHome"
                ? "forHome"
                : null;
            int pageIdValue = pageId == null ? 1 : int.Parse(pageId);
            int categoryId = 0;

            var furnitures = id <= 0 || id == null
                ? _FurnitureData.GetLastFurnitures()
                : _FurnitureData.GetByType(id.Value);

            if (filter == "forOffice")
            {
                furnitures = furnitures.Where(x => x.ForOffice);
            }
            else if (filter == "forHome")
            {
                furnitures = furnitures.Where(x => !x.ForOffice);
            }

            int allCount = furnitures.Count();
            int start = 15 * (pageIdValue - 1);
            int lastCount = allCount - start;
            int count = lastCount < 15 ? lastCount : 15;

            decimal helper = (decimal)allCount / (decimal)15;
            var pagesCount = Math.Ceiling(helper);

            if (count < 1)
            {
                return View(nameof(Grid));
            }

            if (sortOrder == "byPrice")
            {
                furnitures = furnitures.OrderBy(x => x.Price);
            }
            else if (sortOrder == "byPriceDesc")
            {
                furnitures = furnitures.OrderByDescending(x => x.Price);
            }

            var returnList = furnitures.ToList().GetRange(start, count);

            ViewBag.usedFilter = "Grid";
            ViewBag.usedPage = pageIdValue;
            ViewBag.usedCategory = categoryId;
            ViewBag.pagesCount = pagesCount;
            ViewBag.allCount = allCount;
            ViewBag.SordOrder = sortOrder;

            return View(returnList.ToView());
        }

        public IActionResult FindAny(string search, string filter, [FromQuery(Name = "page")] string pageId = null, [FromForm(Name = "sortOrder")] string sortOrder = null)
        {
            int pageIdValue = pageId == null ? 1 : int.Parse(pageId);

            var furnitures = _FurnitureData.FindAnyByName(search);

            if (filter == "forOffice")
            {
                furnitures = furnitures.Where(x => x.ForOffice);
            }
            else if (filter == "forHome")
            {
                furnitures = furnitures.Where(x => !x.ForOffice);
            }

            int allCount = furnitures.Count();
            int start = 15 * (pageIdValue - 1);
            int lastCount = allCount - start;
            int count = lastCount < 15 ? lastCount : 15;
            ViewBag.filter = filter == "forOffice"
            ? "forOffice"
            : filter == "forHome"
                ? "forHome"
                : null;

            if (count < 1)
            {
                return View(nameof(Grid));
            }

            if (sortOrder == "byPrice")
            {
                furnitures = furnitures.OrderBy(x => x.Price);
            }
            else if (sortOrder == "byPriceDesc")
            {
                furnitures = furnitures.OrderByDescending(x => x.Price);
            }

            decimal helper = (decimal)allCount / (decimal)15;
            var pagesCount = Math.Ceiling(helper);

            var returnList = furnitures.ToList().GetRange(start, count);

            ViewBag.usedFilter = "FindAny";
            ViewBag.usedFilterString = search;
            ViewBag.usedPage = pageIdValue;
            ViewBag.usedCategory = 0;
            ViewBag.pagesCount = pagesCount;
            ViewBag.allCount = allCount;
            ViewBag.SordOrder = sortOrder;

            return View(nameof(Grid), returnList.ToView());
        }
        public IActionResult GridByCategory(int id, [FromQuery(Name = "filter")] string filter = null)
        {
            var furnitures = _FurnitureData.GetByCategory(id);

            if (filter == "forOffice")
            {
                furnitures = furnitures.Where(x => x.ForOffice);
            }
            else if (filter == "forHome")
            {
                furnitures = furnitures.Where(x => !x.ForOffice);
            }

            ViewBag.filter = filter == "forOffice"
                ? "forOffice"
                : filter == "forHome"
                    ? "forHome"
                    : null;

            if (furnitures is null)
                return View(nameof(Grid));

            string url = $"/Furniture/ViewPageByCategory?page=1&categoryId={id}";
            if (filter != null)
                url += $"&filter={filter}";

            return Redirect(url);
        }

        public IActionResult ViewPageByCategory([FromQuery(Name = "page")] string id, [FromQuery(Name = "categoryId")] string catId, [FromForm(Name = "sortOrder")] string sortOrder = null, [FromQuery(Name = "filter")] string filter = null)
        {
            int pageId = id == null ? 1 : int.Parse(id);
            int categoryId = int.Parse(catId);
            var furnitures = _FurnitureData.GetByCategory(categoryId);

            if (filter == "forOffice")
            {
                furnitures = furnitures.Where(x => x.ForOffice);
            }
            else if (filter == "forHome")
            {
                furnitures = furnitures.Where(x => !x.ForOffice);
            }

            int start = 15 * (pageId - 1);
            int allCount = furnitures.Count();
            int lastCount = allCount - start;
            int count = lastCount < 15 ? lastCount : 15;

            decimal helper = (decimal)allCount / (decimal)15;
            var pagesCount = Math.Ceiling(helper);
            ViewBag.filter = filter == "forOffice"
            ? "forOffice"
            : filter == "forHome"
                ? "forHome"
                : null;

            if (count < 1)
            {
                return View(nameof(Grid));
            }

            if (sortOrder == "byPrice")
            {
                furnitures = furnitures.OrderBy(x => x.Price);
            }
            else if (sortOrder == "byPriceDesc")
            {
                furnitures = furnitures.OrderByDescending(x => x.Price);
            }

            var returnList = furnitures.ToList().GetRange(start, count);

            ViewBag.usedFilter = "ViewPageByCategory";
            ViewBag.usedPage = pageId;
            ViewBag.usedCategory = catId;
            ViewBag.pagesCount = pagesCount;
            ViewBag.allCount = allCount;
            ViewBag.SordOrder = sortOrder;

            return View($"Grid", returnList.ToView());
        }

        public IActionResult Create() => View(new FurnitureViewModel());

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Create(FurnitureViewModel viewModel, string type)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            var model = viewModel.FromView();
            model.TypeId = _FurnitureData.FindByName(type).Id;

            _FurnitureData.Add(model);
            _FurnitureData.SaveChanges();

            return Redirect($"Index/{model.Id}");
        }

        public IActionResult Edit(int? Id)
        {
            if (Id is null || Id < 0)
                return View(new FurnitureViewModel());

            var furniture = _FurnitureData.GetById((int)Id);

            if (furniture is null)
                return NotFound();

            return View(furniture.ToView());
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Edit(FurnitureViewModel furnitureViewModel, string type)
        {
            if (furnitureViewModel is null)
                throw new ArgumentNullException(nameof(furnitureViewModel));

            if (!ModelState.IsValid)
                return View(furnitureViewModel);

            var model = furnitureViewModel.FromView();

            var id = furnitureViewModel.Id;
            if (id == 0)
                _FurnitureData.Add(model);
            else
            {
                if (type != null)
                {
                    var typeId = _FurnitureData.FindByName(type).Id;

MebelMarket/Views/Shared/_Layout.cshtml
@using MebelMarket.Infrastructure.Interfaces
@using MebelMarket.Infrastructure.Mapping
@inject IFurnitureData catalog;

<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="shortcut icon" href="~/images/favicon.ico" type="image/png">
    <link rel="stylesheet" href="~/css/vendor/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/vendor/plaza-icon.css">
    <link rel="stylesheet" href="~/css/vendor/jquery-ui.min.css">
    <link rel="stylesheet" href="~/css/plugins/slick.css">
    <link rel="stylesheet" href="~/css/plugins/animate.min.css">
    <link rel="stylesheet" href="~/css/plugins/nice-select.css">
    <link rel="stylesheet" href="~/css/plugins/venobox.min.css">
    <link rel="stylesheet" href="~/css/style.css">
</head>

<body>
    <header class="header-section d-lg-block d-none">
        <div class="header-top">
            <div class="container">
                <div class="row d-flex justify-content-between align-items-center">
                    <div class="col-6">
                        <div class="header-top--left">
                            <span>Добро пожаловать в наш магазин!</span>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="header-top--right">
                            <ul class="header-user-menu">
                                <li>
                                    @if (ViewBag.filter == null)
                                    {
                                        <a asp-controller="Furniture" asp-action="Categories">Мебель по категориям</a>
                                    }
                                    else if (ViewBag.filter == "forOffice")
                                    {
                                        <a asp-controller="Furniture" asp-action="Categories" asp-route-filter="@ViewBag.filter">Офисная мебель по категориям</a>
                                    }
                                    else if (ViewBag.filter == "forHome")
                                    {
                                        <a asp-controller="Furniture" asp-action="Categories" asp-route-filter="@ViewBag.filter">Мебель для дома по категориям</a>
                                    }
                                </li>
                                <li>
                                    <a asp-controller="Home" asp-action="Delivery">Доставка</a>
                                </li>
                                <li>
                                    <a asp-controller="Home" asp-action="Payment">Оплата</a>
                                </li>
                                <li>
                                    <a asp-controller="Home" asp-action="AboutUs">О Нас</a>
                                </li>
                                <li>
                                    <a asp-controller="Home" asp-action="Contacts">Контакты</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-center">
            <div class="container">
                <div class="row d-flex align-items-center">
                    <div class="col-3">

                        <div class="header-logo">
                            <a asp-controller="Home" asp-action="Index"><img src="~/images/logo/logo.png" alt="Мебель маркет"></a>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="header-search">
                            <form asp-controller="Furniture" asp-action="FindAny" method="post">
                                <div class="header-search-box default-search-style d-flex">
                                    <input class="default-search-style-input-box border-around border-right-none" type="search" name="Search" placeholder="Что Вы ищете?" required>
                                    <button class="default-search-style-input-btn" type="submit"><i class="icon-search"></i></button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-3 text-right">
                        <partial name="Partial/_SocialLinks" model="Model" />
                    </div>
                </div>
            </div>
        </div>
        <div class="header-bottom sticky-header">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="main-menu">
                            <nav>
                                <ul style="text-align: center;">
                                    <partial name="Partial/_Categories" model="@catalog.GetAllTypes().ToView()" />
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="mobile-header-section d-block d-lg-none">
        <div class="mobile-header-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-12 d-flex justify-content-between align-items-center">
                        <div class="mobile-header--left">
                            <a asp-controller="Home" asp-action="Index" class="mobile-logo-link"> 
                                <img src="~/images/logo/logo.png" alt="" class="mobile-logo-img">
                            </a>
                        </div>
                        <div class="mobile-header--right">
                            <a href="#mobile-menu-offcanvas" class="mobile-menu offcanvas-toggle">
                                <span class="mobile-menu-dash"></span>
                                <span class="mobile-menu-dash"></span>
                                <span class="mobile-menu-dash"></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="mobile-menu-offcanvas" class="offcanvas offcanvas-leftside offcanvas-mobile-menu-section">
        <div class="offcanvas-header text-right">
            <button class="offcanvas-close"><i class="fa fa-times"></i></button>
        </div>
        <div class="offcanvas-mobile-menu-wrapper">
            <div class="mobile-menu-top">
                <span>Добро пожаловать в МебельМаркет!</span>
            </div>
            <div class="mobile-menu-center">
                <form asp-controller="Furniture" asp-action="FindAny" method="post">
                    <div class="header-search-box default-search-style d-flex">
                        <input class="default-search-style-input-box border-around border-right-none" type="search" name="search" placeholder="Что Вы ищете?" required>
                        <button class="default-search-style-input-btn" type="submit"><i class="icon-search"></i></button>
                    </div>
                </form>
                <div class="mobile-menu-customer-support">
                    <div class="mobile-menu-customer-support-icon">
                        <img src="~/images/icon/support-icon.png" alt="">
                    </div>
                    <div class="mobile-menu-customer-support-text">
                        <span>Контактный телефон</span>
                        <a class="mobile-menu-customer-support-text-phone" href="tel:(+7)9373216103">+7-937321-61-03</a>
                    </div>
                </div>
            </div>
            <div class="mobile-menu-bottom">
                <div class="offcanvas-menu">
                    <ul>
                        <li>
                            <a href="#"><span>Главная</span></a>
                            <ul class="mobile-sub-menu">
                                <li><a asp-controller="Furniture" asp-action="Grid" asp-route-id="0" asp-route-filter="forHome">Мебель для дома</a></li>
                                <li><a asp-controller="Furniture" asp-action="Grid" asp-route-id="0" asp-route-filter="forOffice">Офисная мебель</a></li>
                            </ul>
                        </li>
                        <partial name="Partial/_CategoriesMobile" model="@catalog.GetAllTypes().ToView()" />
                        <li><a asp-controller="Home" asp-action="Delivery">Доставка</a></li>
                        <li><a asp-controller="Home" asp-action="Payment">Оплата</a></li>
                        <li><a asp-controller="Home" asp-action="AboutUs">О нас</a></li>
                        <li><a asp-controller="Home" asp-action="Contacts">Контакты</a></li>
                    </ul>
                </div>
                <a class="mobile-menu-email icon-text-right" href="mailto:mebelmarket@mail.ru"><i class="fa fa-envelope-o"> mebelmarket@mail.ru</i></a>

                <br />


            </div>
        </div>
    </div>

    <div class="offcanvas-overlay"></div>

    @RenderBody()

    <footer class="footer-section section-top-gap-100" style="margin-top: 35px;">
        <div class="footer-top section-inner-bg">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <div class="footer-widget footer-widget-contact">
                            <div class="footer-contact">
                                <div class="customer-support">
                                    <div class="customer-support-icon">
                                        <img src="~/images/icon/support-icon.png" alt="">
                                    </div>
                                    <div class="customer-support-text">
                                        <span>Контактный телефон</span>
                                        <a class="customer-support-text-phone" href="tel:(+7)9373216103">+7-937-321-61-03</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="mobile-menu-customer-support">
                            <partial name="Partial/_SocialLinks" model="Model" />
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="footer-widget footer-widget-menu">
                            <h3 class="footer-widget-title"  style="margin-top: 10px; text-align: center;">Информация</h3>
                            <div class="footer-menu">
                                <ul class="footer-menu-nav">
                                    <li><a asp-controller="Home" asp-action="Delivery">Доставка</a></li>
                                    <li><a asp-controller="Home" asp-action="Payment">Оплата</a></li>
                                </ul>
                                <ul class="footer-menu-nav">
                                    <li><a asp-controller="Home" asp-action="AboutUs">О нас</a></li>
                                    <li><a asp-controller="Home" asp-action="Contacts">Контакты</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-md-6">
                        <div class="copyright-area">
                            <p class="copyright-area-text">Copyright © 2021 <a class="copyright-link" asp-controller="Home" asp-action="Index">МебельМаркет</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <button class="material-scrolltop" type="button"></button>

    <script src="~/js/vendor/modernizr-3.11.2.min.js"></script>
    <script src="~/js/vendor/jquery-3.5.1.min.js"></script>
    <script src="~/js/vendor/jquery-migrate-3.3.0.min.js"></script>
    <script src="~/js/vendor/bootstrap.bundle.min.js"></script>
    <script src="~/js/vendor/jquery-ui.min.js"></script>

    <script src="~/js/plugins/slick.min.js"></script>
    <script src="~/js/plugins/material-scrolltop.js"></script>
    <script src="~/js/plugins/jquery.nice-select.min.js"></script>
    <script src="~/js/plugins/jquery.zoom.min.js"></script>
    <script src="~/js/plugins/venobox.min.js"></script>

    <script src="~/js/main.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>